### ISSUE TITLE
DragableLines are not being created between 2 nodes

### ISSUE THREAD

**Issue by kashmoneygt** [ezilox/react-native-node-view#1]
Hi there,

I am trying to use your library to render a simple graph in React Native.

I'm using one of your example code snippets, but unfortunately edges aren't being created between 2 nodes.
I suspect it may have to do with the bugfix commit you added 3 months ago.

I was wondering if you can help me out by re-running your code using this snippet and seeing if you get connected edges between nodes.

Snippet:
```
<View style={{ width: '90%', height: '50%', alignSelf: 'center', borderWidth: 1, borderRadius: 10, borderColor: 'gray' }}>
        <NodeView
          enablePan={true}
          enableZoom={true}
          nodesGroups={[
            {
              nodes: [{ id: '2' }, { id: '3' }],
            },
            {
              nodes: [{ id: '1', lineTo: ['2', '3'], onPress: (id: string) => console.log(id) }],
            },

          ]}
        />
      </View>
```

Image:
![image](https://user-images.githubusercontent.com/21366611/137423164-2e247000-734b-4588-b56d-0d19fa4bb667.png)

**Comment by kashmoneygt** [comment]
For more context, I added some prints to debug this. It seems like for each (n1, n2) pair to make a line between, either one or both of these is always undefined within `nodesLayout`.

Where I added prints:
![image](https://user-images.githubusercontent.com/21366611/137423499-fbd66189-f7cd-42cd-9dbc-93db44b077d5.png)

Prints:
![image](https://user-images.githubusercontent.com/21366611/137423612-b2785ec9-738c-4679-8575-2665a1293918.png)
![image](https://user-images.githubusercontent.com/21366611/137423634-3deb348f-6834-4a1d-9ef6-018df7f71a68.png)

**Comment by ezilox** [comment]
Yes, I will check it right away and will update you.

**Comment by ezilox** [comment]
Hi @kashmoneygt,
The issue has been fixed and now you can use react native web with this package.
Just update to the new version of the package react-native-node-view@1.0.8.
You can view the fix with the last commit I did.
Have a nice weekend.

**Comment by kashmoneygt** [comment]
WOW Thank you so much for such a quick fix! I'll be sure to try it out!
